sets.exported={
    main="Aeneas",
    sub={ name="Skinflayer", augments={'Weapon Skill Acc.+1','Accuracy+24','DMG:+17',}},
    ammo="Seeth. Bomblet +1",
    head="Skulker's Bonnet",
    body="Mummu Jacket +1",
    hands={ name="Floral Gauntlets", augments={'Rng.Acc.+15','Accuracy+15','"Triple Atk."+3','Magic dmg. taken -4%',}},
    legs="Mummu Kecks +1",
    feet="Mummu Gamash. +1",
    neck="Lissome Necklace",
    waist="Kentarch Belt",
    left_ear="Cessance Earring",
    right_ear="Sherida Earring",
    left_ring="Hetairoi Ring",
    right_ring="Cacoethic Ring +1",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10',}},
}